version: '3'

services:
  pms-db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

